#!/bin/bash

source GoboPath
source $goboSettings/BootOptions

if [ "$UserDefinedModules[*]" ]
then
   for m in "${UserDefinedModules[@]}"
   do
      # eval is used so that m can look like "foo='bar baz' bar=qux"
      [ ! -z "$m" ] && eval modprobe "$m" || true
   done
fi
