#!/bin/sh
Exec "Remounting root file system..."         mount -n -o remount,rw /
Exec "Cleaning mtab and boot settings..."     rm -f "$goboSettings/mtab"*
Exec "Cleaning up any stale lock files..."    eval "find $goboVariable/{run,lock}/ -type f | grep -v utmp | xargs -i rm -rf {}; rm -rf  $goboTemp/.X*-lock"
Exec "Starting Udev..."                       Udev Start

Daemon                                        klogd -n -c 1
Daemon                                        syslogd -n -m 0

Exec "Checking remaining file systems..."     fsck -p -C -T -A -R
Exec "Hiding legacy tree..."                  GoboHide Start
Exec "Setting clock..."                       SetClock Start
Exec "Creating new mtab..."                   mount -o remount,rw /
Exec "Mounting local file systems..."         mount -a -f -t nonfs,nosmbfs,nocifs,noproc,noswap,nodevpts,nosysfs
Exec "Activating all swap files/partitions..." swapon -a
Exec "Linking kernel modules directory..."    ln -nfs "$goboModules"/`uname -r` "$goboLibraries"/modules/`uname -r`
Exec "Setting hostname to $HostName..."       hostname "$HostName"

[ "${UserDefinedModules[*]}" ] && \
Exec "Loading user-defined kernel modules..." LoadModules

Exec "Creating utmp and wtmp..."              CreateChmod 644 $goboVariable/{run/utmp,log/wtmp}
Exec "Removing one-time boot settings..."     rm -f $goboSettings/nologin /fastboot /forcefsck

#Exec "Starting PCMCIA daemon..."             PCMCIA Start
#Exec "Starting ssh daemon..."		          OpenSSH Start
Exec "Mounting network file systems..."       mount -a -t nfs,smbfs,cifs
#Exec "Loading sound settings..."             Alsactl Start
Exec "Starting message bus..."                MessageBus Start
Exec "Initializing network..."                connmand
Exec "Loading keymap..."                      loadkeys "$KeymapLayout"
