#!/bin/sh

# Remount root file system read-write
mount -n -o remount,rw /

# Make mtab a symlink to /proc/mounts
rm -f "$goboSettings/mtab"*
ln -s /proc/mounts "$goboSettings/mtab"

# Launch udev
Udev Start
ThemeClear

Daemon                                        klogd -n -c 1
Daemon                                        syslogd -n -m 0

Exec "Checking remaining file systems..."     fsck -p -C -T -A -R
Exec "Hiding legacy tree..."                  GoboHide Start
Exec "Setting clock..."                       SetClock Start
Exec "Mounting local file systems..."         mount -a -f -t nonfs,nosmbfs,nocifs,noproc,noswap,nodevpts,nosysfs

# Mount pseudo-filesystems
mount /System/Kernel/Objects
mount /System/Kernel/Status
mount /System/Kernel/Devices
mount /dev/shm

# Configure loopback device
ifconfig lo 127.0.0.1

Exec "Activating all swap files/partitions..." swapon -a &
Exec "Setting hostname to $HostName..."       hostname "$HostName"

[ "${UserDefinedModules[*]}" ] && \
Exec "Loading user-defined kernel modules..." LoadModules

Exec "Creating utmp and wtmp..."              CreateChmod 644 $goboVariable/{run/utmp,log/wtmp}
#Exec "Starting PCMCIA daemon..."             PCMCIA Start
#Exec "Starting ssh daemon..."		      OpenSSH Start
#Exec "Mounting network file systems..."      mount -a -t nfs,smbfs,cifs
Exec "Loading sound settings..."              Alsactl Start
Exec "Starting message bus..."                MessageBus Start
Exec "Starting ACPI daemon..."                Acpid Start
Exec "Configuring power settings..."          PowerTOP Start
Exec "Launching Listener daemon..."           Listener Start
Exec "Loading keymap..."                      loadkeys "$KeymapLayout"
